# Generated by Django 5.0.7 on 2025-01-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
