# Generated by Django 5.0.7 on 2025-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumble',
            field=models.URLField(blank=True, null=True),
        ),
    ]
